import { app, ipcMain, IpcMainInvokeEvent, BrowserWindow } from "electron";
import sqlite from "better-sqlite3";
import fs from "fs";
import {
  createDB,
  getTasks,
  addTask,
  modifyTask,
  completeTask,
  deleteTask,
  cleanupTasks,
} from "./utils/db.utils";
import { task } from "./types/data.types";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const SETTINGS_WINDOW_WEBPACK_ENTRY: string;
declare const SETTINGS_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle database location
// TODO: move this to DOTENV
export const dbLoc =
  "/Users/psilentrain1/Documents/development/jdt-apps-todos/.private/todos.db";

// DB connection
export const db = new sqlite(dbLoc);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  // Run startup tasks
  startupTasks();

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    show: false,
    frame: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.maximize();
  mainWindow.show();
};

const createSettingsWindow = (): void => {
  const settingsWindow = new BrowserWindow({
    height: 600,
    width: 400,
    webPreferences: {
      preload: SETTINGS_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  settingsWindow.loadURL(SETTINGS_WINDOW_WEBPACK_ENTRY);

  settingsWindow.show();
};

// APP Controls
ipcMain.handle("appClose", () => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (focusedWindow) {
    focusedWindow.close();
  }
});

ipcMain.handle("appMinimize", () => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (focusedWindow) {
    focusedWindow.minimize();
  }
});

// TASK Controls
ipcMain.handle("getTasks", () => {
  const tasks = getTasks();
  return tasks;
});

ipcMain.handle("addTask", async (event: IpcMainInvokeEvent, task: task) => {
  if (addTask(task)) {
    return getTasks();
  }
});

ipcMain.handle(
  "modifyTask",
  async (
    event: IpcMainInvokeEvent,
    id: string,
    content: string,
    modified: string,
  ) => {
    if (modifyTask(id, content, modified)) {
      return getTasks();
    }
  },
);

ipcMain.handle(
  "completeTask",
  async (event: IpcMainInvokeEvent, id: string, completed: string) => {
    if (completeTask(id, completed)) {
      return getTasks();
    }
  },
);

ipcMain.handle("deleteTask", async (event: IpcMainInvokeEvent, id: string) => {
  if (deleteTask(id)) {
    return getTasks();
  }
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

/**
 * Items to run at startup.
 */
function startupTasks() {
  const file = fs.readFileSync(dbLoc);
  if (file) {
    if (file.length === 0) {
      createDB();
    }
  }

  cleanupTasks();
}
